name: flutter_stack_trace
description: A package for manipulating flutter stack traces and printing them readably,base on stack_trace
repository: https://github.com/crazecoder/flutter_stack_trace
version: 1.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.12.0'

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter